{ "msg": "Se ha producido un error durante la validaci√≥n del usuario" }
